import Foundation

public struct CaptureSettings: Equatable, Sendable {
    public var ignoreConfidential: Bool
    public var ignoreTransient: Bool
    public var ignoredApps: Set<String>

    public init(ignoreConfidential: Bool = true, ignoreTransient: Bool = true, ignoredApps: Set<String> = ["com.apple.keychainaccess"]) {
        self.ignoreConfidential = ignoreConfidential
        self.ignoreTransient = ignoreTransient
        self.ignoredApps = Set(ignoredApps.map { $0.lowercased() })
    }
}

/// Decides whether a pasteboard change is recorded. Defaults mirror Paste: skip concealed and transient content.
public enum CapturePolicy {
    public enum SkipReason: Equatable, Sendable { case confidential, transient, ignoredApp, empty, ownWrite }
    public enum Decision: Equatable, Sendable { case capture, skip(SkipReason) }

    public static let ownMarkerType = "app.clipboardx.internal"
    private static let confidentialTypes: Set<String> = ["org.nspasteboard.ConcealedType"]
    private static let transientTypes: Set<String> = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    public static func decision(types: [String], sourceBundleID: String?, settings: CaptureSettings) -> Decision {
        if types.isEmpty { return .skip(.empty) }
        if types.contains(ownMarkerType) { return .skip(.ownWrite) }
        if let source = sourceBundleID?.lowercased(), settings.ignoredApps.contains(source) { return .skip(.ignoredApp) }
        if settings.ignoreConfidential, !confidentialTypes.isDisjoint(with: types) { return .skip(.confidential) }
        if settings.ignoreTransient, !transientTypes.isDisjoint(with: types) { return .skip(.transient) }
        return .capture
    }
}
