import XCTest
@testable import ClipboardXKit

final class CapturePolicyTests: XCTestCase {
    private let text = ["public.utf8-plain-text"]
    private let strict = CaptureSettings(ignoreConfidential: true, ignoreTransient: true, ignoredApps: ["com.apple.keychainaccess"])

    func testNormalTextIsCaptured() {
        XCTAssertEqual(CapturePolicy.decision(types: text, sourceBundleID: "com.apple.Terminal", settings: strict), .capture)
    }

    func testConcealedSkippedOnlyWhenEnabled() {
        let types = text + ["org.nspasteboard.ConcealedType"]
        XCTAssertEqual(CapturePolicy.decision(types: types, sourceBundleID: nil, settings: strict), .skip(.confidential))
        let lax = CaptureSettings(ignoreConfidential: false, ignoreTransient: true, ignoredApps: [])
        XCTAssertEqual(CapturePolicy.decision(types: types, sourceBundleID: nil, settings: lax), .capture)
    }

    func testTransientAndAutoGeneratedSkipped() {
        XCTAssertEqual(CapturePolicy.decision(types: text + ["org.nspasteboard.TransientType"], sourceBundleID: nil, settings: strict), .skip(.transient))
        XCTAssertEqual(CapturePolicy.decision(types: text + ["org.nspasteboard.AutoGeneratedType"], sourceBundleID: nil, settings: strict), .skip(.transient))
    }

    func testIgnoredAppSkippedCaseInsensitively() {
        XCTAssertEqual(CapturePolicy.decision(types: text, sourceBundleID: "com.apple.KeychainAccess", settings: strict), .skip(.ignoredApp))
    }

    func testEmptyAndOwnWritesSkipped() {
        XCTAssertEqual(CapturePolicy.decision(types: [], sourceBundleID: nil, settings: strict), .skip(.empty))
        XCTAssertEqual(CapturePolicy.decision(types: text + [CapturePolicy.ownMarkerType], sourceBundleID: nil, settings: strict), .skip(.ownWrite))
    }
}
