import AppKit
import SwiftUI

private enum Pane: String, CaseIterable, Identifiable {
    case general = "General", privacy = "Privacy", shortcuts = "Shortcuts"
    var id: String { rawValue }
    var symbol: String {
        switch self { case .general: return "gearshape"; case .privacy: return "hand.raised"; case .shortcuts: return "keyboard" }
    }
}

struct SettingsView: View {
    @ObservedObject var settings: AppSettings
    let backupStatus: () -> String
    let backupNow: () -> Void
    let libraryPath: String
    @State private var pane: Pane = .general

    var body: some View {
        HStack(spacing: 0) {
            VStack(alignment: .leading, spacing: 4) {
                ForEach(Pane.allCases) { item in
                    Button { pane = item } label: {
                        Label(item.rawValue, systemImage: item.symbol)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.horizontal, 10).padding(.vertical, 7)
                            .background(pane == item ? Color.accentColor : Color.clear, in: RoundedRectangle(cornerRadius: 8))
                            .foregroundStyle(pane == item ? Color.white : Color.primary)
                    }.buttonStyle(.plain)
                }
                Spacer()
            }
            .padding(12).frame(width: 190)
            Divider()
            ScrollView {
                VStack(alignment: .leading, spacing: 18) {
                    Text(pane.rawValue).font(.title2.bold())
                    switch pane {
                    case .general: general
                    case .privacy: privacy
                    case .shortcuts: shortcuts
                    }
                }
                .padding(24).frame(maxWidth: .infinity, alignment: .leading)
            }
        }
        .frame(width: 720, height: 560)
    }

    private var general: some View {
        VStack(alignment: .leading, spacing: 18) {
            card {
                Toggle("Open at login", isOn: Binding(get: { settings.openAtLogin }, set: { settings.openAtLogin = $0 }))
                Toggle("iCloud backup", isOn: $settings.icloudBackup)
                HStack {
                    Text(backupStatus()).font(.callout).foregroundStyle(.secondary)
                    Spacer()
                    Button("Back up now", action: backupNow)
                }
                Toggle("Sound effects", isOn: $settings.soundEffects)
            }
            Text("Paste Items").font(.headline)
            card {
                Picker("", selection: $settings.pasteToActiveApp) {
                    VStack(alignment: .leading) { Text("To active app"); Text("Paste selected items directly into the app you are using.").font(.caption).foregroundStyle(.secondary) }.tag(true)
                    VStack(alignment: .leading) { Text("To clipboard"); Text("Copy selected items to the system clipboard to paste manually later.").font(.caption).foregroundStyle(.secondary) }.tag(false)
                }.pickerStyle(.radioGroup).labelsHidden()
                Toggle("Always paste as Plain Text", isOn: $settings.alwaysPlainText)
            }
            Text("Keep History").font(.headline)
            card {
                HStack { Text("Forever"); Spacer(); Image(systemName: "infinity") }
                Text("History is never deleted automatically. Nothing you copied is lost.").font(.caption).foregroundStyle(.secondary)
            }
            Text("Library: \(libraryPath)").font(.caption).foregroundStyle(.secondary).textSelection(.enabled)
        }
    }

    private var privacy: some View {
        VStack(alignment: .leading, spacing: 18) {
            card {
                Toggle(isOn: $settings.ignoreConfidential) {
                    VStack(alignment: .leading) { Text("Ignore confidential content"); Text("Do not save passwords and sensitive data when detected.").font(.caption).foregroundStyle(.secondary) }
                }
                Toggle(isOn: $settings.ignoreTransient) {
                    VStack(alignment: .leading) { Text("Ignore transient content"); Text("Do not save temporary data generated by other apps.").font(.caption).foregroundStyle(.secondary) }
                }
            }
            Text("Ignore Applications").font(.headline)
            Text("Do not save content copied from the applications below.").font(.caption).foregroundStyle(.secondary)
            card {
                ForEach(settings.ignoredApps, id: \.self) { bundle in
                    HStack {
                        Text(bundle)
                        Spacer()
                        Button { settings.ignoredApps.removeAll { $0 == bundle } } label: { Image(systemName: "minus.circle") }.buttonStyle(.plain)
                    }
                }
                Button("Add Application…") { addApp() }
            }
        }
    }

    private var shortcuts: some View {
        card {
            row("Show ClipboardX", "⇧⌘V")
            row("Next / previous pinboard", "⌘→  ⌘←")
            row("Quick paste", "⌘1 … ⌘9")
            row("Paste selected", "Return")
            row("Plain text mode", "⇧ with Return or ⌘1…9")
            row("Close", "Esc")
        }
    }

    private func row(_ title: String, _ keys: String) -> some View {
        HStack { Text(title); Spacer(); Text(keys).font(.system(.body, design: .monospaced)).padding(.horizontal, 8).padding(.vertical, 2).background(Color.secondary.opacity(0.2), in: RoundedRectangle(cornerRadius: 6)) }
    }

    private func card<Content: View>(@ViewBuilder _ content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 12, content: content)
            .padding(14).frame(maxWidth: .infinity, alignment: .leading)
            .background(Color.secondary.opacity(0.12), in: RoundedRectangle(cornerRadius: 10))
    }

    private func addApp() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.application]
        panel.directoryURL = URL(fileURLWithPath: "/Applications")
        guard panel.runModal() == .OK, let url = panel.url, let bundle = Bundle(url: url)?.bundleIdentifier else { return }
        let id = bundle.lowercased()
        if !settings.ignoredApps.contains(id) { settings.ignoredApps.append(id) }
    }
}
